theme = "hugo-assembly"
baseURL = "https://agcred.tech"
languageCode = "en-US"
title = "AGCred"

# Metadata
[params]
  author = "Luiz Fernando P. Droubi"
  description = "The description"

# banner section (from here on is for assembly theme)
[params.banner]
  title = "AGCred Financeira"
  byline = "Serviços financeiros de qualidade para você e sua família."

[params.actions] # CTAs
  enable = true
  register = "CTA Now!"

# Navigation section
[params.nav]
  home = "Início"
  services = "Serviços"
  welcome = "Bem-vindo"
  contact = "Contacte-nos"

# Services section
[params.services]
  enable = true
  title = "Serviços"
  subtitle = "Na AGCred você encontra os melhores produtos financeiros. Somos especializados em crédito consignado para servidores públicos, aposentados e pensionistas."

  [[params.services.item]]
    weight = "A"
    description = "Crédito rápido e fácil para seus projetos, servidor público."
    button_item_info = "Servidores públicos"

  [[params.services.item]]
    weight = "B"
    description = "Na AGCred aposentados e pensionistas têm sempre a nossa preferência, para ajudar nos momentos mais alegres ou mais difíceis da sua vida. Consulte nossas opções de cartões."
    button_item_info = "Aposentados e pensionistas"

  [[params.services.item]]
    weight = "C"
    description = "Se você pretende comprar ou trocar de carro, temos especialistas para ajudá-los da melhor forma."
    button_item_info = "Veículos"

# Welcome section
[params.welcome]
  enable = true
  title = "Venha para a AGCred"
  subtitle = "Computing the conversion of instructions in low-level code to machine code by an assembler."
  description = "This is <strong>Assembly</strong>, a free, fully standards-compliant CSS template designed by <a href=\"http://templated.co\" rel=\"nofollow\">TEMPLATED</a>. The photos in this template are from <a href=\"http://fotogrph.com/\"> Fotogrph</a>. This free template is released under the <a href=\"http://templated.co/license\">Creative Commons Attribution</a> license, so you're pretty much free to do whatever you want with it (even use it commercially) provided you give us credit for it. Have fun :)"
  button_text = "Call Now"

# Contact section
[params.contact]
  enable = true
#   title = "Get In Touch"
#   message = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet nam itaque ipsam iste provident quo ipsam iste provident."
#   name_placeholder = "Your name"
#   email_placeholder = "Your email"
#   email_disclaimer = "We'll never share your email with anyone else."
#   message_placeholder = "Please enter a message."
#   button_text = "Submit"

# Footer section
[params.footer]
  enable = true
  copy = "2018 &copy; Assembly Inc. | All rights reserved"
  twitter = ""
  facebook = ""
  instagram = ""

